version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - fx-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - fx-network
  rate-service:
    build: ./fx-rate-service
    depends_on:
      - kafka
    networks:
      - fx-network
    ports:
      - "8087:8087"
  alert-service:
    build: ./alert-service
    depends_on:
      - kafka
    networks:
      - fx-network
    ports:
      - "8088:8088"
  api-gateway:
    build: ./api-gateway
    networks:
      - fx-network
    ports:
      - "8086:8086"
networks:
  fx-network:
    driver: bridge
